### ISSUE TITLE
PRを作るところで送る先をfork先でなくこのリポジトリに送ってしまう問題

### ISSUE THREAD

**Issue by Komei22** [challecara/git-training#26]
https://github.com/challecara/git-training/blob/main/doc/pull_request.md

PRを作成する資料のところで、PRをfork先に出してもらうのですが、デフォルトの送り先がこのリポジトリとなっているので、画像などを入れて強調してミスを無くしたい

**Comment by zu-min** [comment]
スクリーンショット入れつつ、こっちじゃなくてこっちだよ！って案内する感じにすれば良さそうか
