### ISSUE TITLE
GitHubのパスワード問題

### ISSUE THREAD

**Issue by zu-min** [challecara/git-training#38]
httpsでgit cloneする場合に、GitHub Accountのパスワードのかわりに、personal access tokenを利用する必要がある
https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

**Comment by hasimoto1009** [comment]
./doc/clone.md にこんな感じで追加でいいんかな

```
4.1 cloneする際にGitHubのログイン情報を求められたら

以下の記事で個人アクセストークンの取得手順を行う(SSH側はやらなくてよい)
[Qiita - GitHubがパスワード認証を廃止するらしいので](https://qiita.com/shiro01/items/e886aa1e4beb404f9038)
```

**Comment by zu-min** [comment]
Qiitaの記事よりは公式のほうが適切かなぁと思うので、URLはこちらが良さそうです。
https://docs.github.com/ja/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

https cloneの場合、ユーザID,パスワードが求められるけど、GitHubに登録したパスワードではなく、個人アクセストークンがパスワードの代わりになる、と最初に書いておくと理解しやすいかもしれないですね
