### ISSUE TITLE
`/chinsk2` エンドポイントを追加する

### ISSUE THREAD

**Issue by chinsk2** [challecara/git-training#39]
## やりたいこと
`/chinsk2` にGetリクエストをすると、 `Hello chinsk2!` と表示される機能を実装する

## 期待する動作
`http://localhost:4567/chinsk2` にアクセスすると、Webブラウザに `Hello chinsk2!` と表示される

**Comment by zu-min** [comment]
forkした先で演習を行うと良いかと思います。
forkの仕方やforkした先での操作が分からない場合はここに書いていただければ回答します。
