### ISSUE TITLE
[ToDo] 2022 8/13

### ISSUE THREAD

**Issue by zu-min** [challecara/git-training#43]
2022 8/13 までに対応しておきたいissueたち

- https://github.com/challecara/git-training/issues/24
- https://github.com/challecara/git-training/issues/38
- https://github.com/challecara/git-training/issues/26
- https://github.com/challecara/git-training/issues/36
- https://github.com/challecara/git-training/issues/37

**Comment by hasimoto1009** [comment]
#26 かな
#37 は無料アカウントの複数アカウント作成は規約違反なのであとまわし

それ以外はPR作成しました

**Comment by zu-min** [comment]
Ubuntu 20.04にしてるけど、22.04が利用できるはずなので上げてもいいかも
https://github.com/challecara/git-training/blame/main/doc/setup-windows.md#L16

**Comment by zu-min** [comment]
https://docs.github.com/ja/site-policy/github-terms/github-terms-of-service#3-account-requirements

> 1 人の個人または 1 つの法人が複数の無料「アカウント」を保持することはできません (コンピュータアカウントも制御することを選択した場合、それは問題ありませんが、それはコンピュータの実行にのみ使用できます)。

これですねー。昔と違って、orgも無料でプライベートリポジトリが利用出来るようになったりもしてるので、研究室等でアカウント分けているようなケースで、規約違反になっちゃってる場合もありそうですね。

**Comment by zu-min** [comment]
GitHubのリンクは修正した。https://github.com/challecara/git-training/pull/48
GitHub以外もありそう・・・

**Comment by zu-min** [comment]
これらを修正する必要がありそう

Docker https://github.com/challecara/git-training/blob/main/doc/setup-mac.md
WSL & Docker https://github.com/challecara/git-training/blob/main/doc/setup-windows.md

**Comment by zu-min** [comment]
#37 は特殊ケースなので、遭遇したら別途対応してもらうってことにしますか。
